### ISSUE TITLE
How do I log to stderr?

### ISSUE THREAD

**Issue by AndrewSav** [serilog/serilog-sinks-console#100]
I would like my program to write machine readable output to stdout and information for humans to stderr. To that end all logging regardless of the log level has to go to stderr and not stdout. How do I configure that?

**Comment by nblumhardt** [comment]
`WriteTo.Console(standardErrorFromLevel: LogEventLevel.Verbose)` should do the job 👍

**Comment by AndrewSav** [comment]
Many thanks @nblumhardt!
