### ISSUE TITLE
Specifying a "theme" argument overrides a "formatter"

### ISSUE THREAD

**Issue by mikejr83** [serilog/serilog-sinks-console#103]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [ ] New Feature
- [x] Unsure/Both

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
Serilog.AspNetCore (3.4.0) -> Serilog.Sinks.Console (3.1.1)

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behaviour you are experiencing?**

I'm unsure if this is correct functionality or is a bug in the Console sink or in the compact formatter code.

When a `theme` argument value is provided in the configuration for a Console sink with a `formatter` set to "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact" the formatter is ignored.

This scenario happens in this case

`appsettings.json`:

```json
{
  "Serilog": {
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
        }
      }
    ]
  }
}
```

`appsettings.production.json`:

```json
{
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact"
        }
      }
    ]
  }
}
```

**Please describe the expected behaviour if the ?**

I would think that the formatter would take precedence over the theme.

**Comment by justhoma** [comment]
The same thing happens if you supply an '_outputTemplate_'.

**Comment by nblumhardt** [comment]
_Serilog.Expressions_'s `ExpressionTemplate` allows both JSON format customization and theming at the same time, worth checking out if you're still interested in this.
