### ISSUE TITLE
serilog.Log.Error()

### ISSUE THREAD

**Issue by bwinchester** [serilog/serilog-sinks-console#104]
- [ X ] netCore 3.0.403 (latest?)
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

We're using serilog.Log.Error() and writeTo Console in our net core 3.x app. Im using rsyslog [omelasticsearch](https://rsyslog.readthedocs.io/en/latest/configuration/modules/omelasticsearch.html) to better index counts of types of logs and time buckets, etc. 

I started to write filters to create a display for [Error] type logs out of our App, running on Ubuntu 18.04 and 20.04. 

I noticed all the syslogseverity-text and syslogseverity-code are Info and 6, respectively. Which 6 is correct for informational logs in rfc5424. for Syslog logs.

Is there something missing in documentation for WriteTo Console of Serilog we are missing to get our app logs to console to flag as Error level 3, Per the specs?

Using Rsyslog Template Below, I can throw an error that calls Serilog.Log.Error(string):

`$template class, "Time: %timestamp%, Facility: %syslogfacility-text%, Priority: %syslogseverity%, Hostname: %hostname%,
Message: %msg%\n"
*.* /var/log/logfile.log;class`

Syslog output explicitly calling out syslogseverity as a 6 for Info, rather than 3 for Error:

`Time: Nov  3 05:23:23, Facility: daemon, Priority: 6, Hostname: api,Time: Nov  3 05:23:23, Facility: daemon, Priority: 6, Hostname: api,Nov  3 05:23:23 api appname[30484]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Nov  3 05:23:23 api appname[30484]:    --- End of inner exception stack trace ---
Nov  3 05:23:23 api appname[30484]:    at Neo4jClient.GraphClient.Connect(NeoServerConfiguration configuration)
Nov  3 05:23:23 api appname[30484]:    at Company.Platform.Data.DAL.AdminDAO..ctor(IOptions`1 neo4jConfig) in /home/gitlab-runner/builds/JTMpT4gz/0/engineering/platform/api/Company.Platform.Data/DAL/AdminDAO.cs:line 34`

Is this Serilog defaulting to Microsoft log severity codes when you dynamically set WriteTo Console in appsettings?
Is it my template for appsettings causing this? Im pretty sure the template has no effect on the severity level called to syslog by serilog though. 

Template
`{
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] ({SourceContext} :: {Method}) {Message}{NewLine}{Exception}"
        }
      },`

**Comment by nblumhardt** [comment]
Hi! Serilog and the console sink have no awareness of syslog/syslog error levels. It sounds like you'll need to look into how your terminal output -> syslog component is configured. HTH!

**Comment by bwinchester** [comment]
Yes, sounds like we need to create a custom Serilog config rather than just using Serilog.Log.Error() or whatever. 

I found a [Serilog Syslog Sink here](https://github.com/IonxSolutions/serilog-sinks-syslog)
