### ISSUE TITLE
Not working on syslog with net50

### ISSUE THREAD

**Issue by JoshClose** [serilog/serilog-sinks-console#110]
- Serilog.AspNetCore 3.4.0
- Published:
  - runtime linux-x64
  - framework net50
  - trimmed
  - single file
- Running on Ubuntu 18.04.1 LTS

When running the app locally, everything works as expected. When running on Unbuntu, logs aren't showing up in syslog. All the `Console.WriteLine`'s are showing up, but not Serilog with the Console sink.

```json
{
	"serilog": {
		"MinimumLevel": {
			"Default": "Debug",
			"Override": {
				"Microsoft": "Warning",
				"System": "Warning"
			}
		},
		"WriteTo": [
			{ "Name": "Console" }
		],
		"Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
	}
}
```

**Comment by nblumhardt** [comment]
Hi Josh - do you get the results you expect when calling `WriteTo.Console()` in C#, rather than via the JSON config? Cheers!

**Comment by JoshClose** [comment]
I'll deploy with that and see.

**Comment by JoshClose** [comment]
Yes, that works.

Here is my setup.

```cs
Console.WriteLine($"Directory.GetCurrentDirectory: {Directory.GetCurrentDirectory()}");
Console.WriteLine($"Environment.CurrentDirectory: {Environment.CurrentDirectory}");

var configuration = new ConfigurationBuilder()
	.SetBasePath(Directory.GetCurrentDirectory())
	.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
	.AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json", optional: true, reloadOnChange: true)
	.AddEnvironmentVariables()
	.Build();

Log.Logger = new LoggerConfiguration()
	.ReadFrom.Configuration(configuration)
	.WriteTo.Console()
	.CreateLogger();
```

I thought maybe the current directory wasn't correct when built with a single file or something, but both the writes at the beginning print the correct location.

I believe this worked before I made some changes a while back; one being a switch to net50. I just noticed it wasn't logging anymore today.

**Comment by nblumhardt** [comment]
Looks like it's this one: https://github.com/serilog/serilog-settings-configuration/#net-50-single-file-applications

**Comment by JoshClose** [comment]
Yes, that works! Thanks!
