### ISSUE TITLE
Is this even needed anymore?

### ISSUE THREAD

**Issue by cgountanis** [serilog/serilog-sinks-console#112]
I just add .WriteTo.Console() without the SINK package and I still get colors and stuff?

![image](https://user-images.githubusercontent.com/14899817/118696148-99212200-b7d3-11eb-829b-ff8bc667b780.png)

**Comment by nblumhardt** [comment]
Certainly is! Looks like you're running it, there - I'd guess it's included in your project via a transitive dependency.

**Comment by cgountanis** [comment]
Strange I assumed I would have to add the nuget package to the project. Cool.

**Comment by nblumhardt** [comment]
👍  -- yeah, dependencies-of-dependencies all end up in scope when using NuGet. Thanks for checking in!
