### ISSUE TITLE
PSA: Rider is currently not displaying the background color of console logs

### ISSUE THREAD

**Issue by JasonLandbridge** [serilog/serilog-sinks-console#116]
Hi 👋

See: https://youtrack.jetbrains.com/issue/RIDER-66109

With the latest version the background color in the console is not working, which is entirely due to Rider. I thought it was this package but can confirm everything is working again after downgrading Rider to 2021.1.5

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Jason.

Do you have more luck using an ANSI console theme? (E.g. `theme: AnsiConsoleTheme.Literate` will give you something approximating the defaults.)

**Comment by JasonLandbridge** [comment]
Yeah I tried that as well, I do get the foreground coloring from that theme but no red background color, on for example "ERR".

**Comment by nblumhardt** [comment]
The `Sixteen` theme in the most recent dev release might improve on this, if the Rider issue is still lurking.

**Comment by JasonLandbridge** [comment]
I can confirm everything in Rider has been fixed regard this!
