### ISSUE TITLE
Request to make renderers and themes public

### ISSUE THREAD

**Issue by kds-jprat** [serilog/serilog-sinks-console#121]
Hi 👋

Would it be possible to make themes and renderers public so that we can create new tokens and extend themes ?

I've been looking onto making a custom ITextFormatter so that I can create extra token renderers that we need to analyze specific output. Beside we are also using an extended version of LogEvent with added properties for specific contexts.

The only way currently is to rewrite the entire rendering code and themes which would make this library practically unused.

Thanks!

**Comment by nblumhardt** [comment]
Thanks for the note! Right now, forking would be the way to go. Your request is reasonable, but this goal isn't included in the original design of those types - to make them suitable for use in a public API we'd need to do a solid review and likely redesign some parts to avoid breaking changes as this library evolves in the future.
