### ISSUE TITLE
Missing Method Exception

### ISSUE THREAD

**Issue by TonyValenti** [serilog/serilog-sinks-console#125]
Hi!  It seems like the latest build of serilog broke binary compatibility.  I'm trying to use the Intuit Quickbooks API connector and I get this error:

```
System.MissingMethodException: 'Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.'
```

Can you please fix and publish an update?

**Comment by nblumhardt** [comment]
Hi, Tony. Breaking changes across major version increments are expected, sounds like you'll need to drop back a version, or get the QB API connector to update (or refactor to remove their sink dependency). Cheers!
