### ISSUE TITLE
Compatibility with .NET 6

### ISSUE THREAD

**Issue by pauloasantos** [serilog/serilog-sinks-console#127]
Hello 👋

Any news about the upgrade to .NET 6 / NetStandard 2.1?

Thanks!

**Comment by nblumhardt** [comment]
Hi! Any reason it doesn't work currently? Thanks!

**Comment by pauloasantos** [comment]
Yes,

This error happens when upgrade net5.0 to net6.0:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'LoggerSinkConfiguration' does not contain a definition for 'Console' and no accessible extension method 'Console' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing a using directive or an assembly reference?)

Code sample:

`var logger = new LoggerConfiguration().WriteTo.Console().CreateLogger();`

**Comment by nblumhardt** [comment]
Looks like you're missing a package reference, a `using Serilog;`, or similar. There's a full example that shows `Console()` in Program.cs with .NET 6 here:

https://github.com/datalust/dotnet6-serilog-example

HTH!

**Comment by pauloasantos** [comment]
@nblumhardt

The problem was in Visual Studio, I restarted my PC and it work very well.

Thanks
