### ISSUE TITLE
Please add net6.0 as a target framework, or remove net5.0 target

### ISSUE THREAD

**Issue by zachrybaker** [serilog/serilog-sinks-console#144]
I have a client who is up in arms because this package "does not support net6.0."

Yes, I know there's a target of NetStandard2.1 being used.

Net5.0 is out of support since May of last year. So I would imagine you can fall in line and swap net5.0 to net6.0. Or just remove the net5.0 target and allow for NetStandard2.1 to do its thing.

Thanks.

**Comment by zachrybaker** [comment]
https://github.com/serilog/serilog-sinks-console/pull/145

**Comment by Numpsy** [comment]
Fixed by #157 ?
