### ISSUE TITLE
Upgrade to .NET 8 and using C# 12 feature

### ISSUE THREAD

**Issue by nimanikoo** [serilog/serilog-sinks-console#155]
Hi 👋

I hope you are doing well.
I was reviewing the project and noticed that .NET 7 is being used for the latest version.
I also noticed some areas in the code where accessor modifiers could be applied, which might be helpful during code review.
I wanted to ask if you have any plans to upgrade to C# 12 and .NET 8?
If you are agreeable, I would be happy to help with the upgrade and submit a pull request for the changes.
I believe that upgrading to C# 12 and .NET 8 would be a positive step for the project and would make it more efficient, scalable, and future-proof.
Please let me know your thoughts on this proposal.

Thank you

**Comment by nblumhardt** [comment]
Thanks for reaching out; we don't need a PR for this currently, thanks.

**Comment by bartelink** [comment]
In general, the satellite projects follow the lead of the Core one - I'm pretty sure these things are being applied there (see PRs by SimonCropp, sungam3r and some others)

There's no problem with updating things to use the v8 SDK; it's a good thing, and everyone is on board with that general concept (i.e. pretty sure PRs won't be rejected, even if ultimately reviewer time is a scarce thing so the time to merge can vary)

Obviously the TargetFrameworks list can't just be changed to `net8.0` only - it should follow the lead of the core packages to the max degree possible (see TFM lists and the comments around it). If you want lots of chapter and verse (aka TMI) on the constraints and considerations, see https://github.com/serilog/serilog/issues/1970

**Comment by nimanikoo** [comment]
@bartelink  Thank you for the complete explanation
