### ISSUE TITLE
Logging inside of the Startup() constructor

### ISSUE THREAD

**Issue by kevingy** [serilog/serilog-sinks-console#18]
I'm having difficulty logging at application start up. The last two lines of my Setup() constructor are:
```
Log.Logger = loggerConfiguration.CreateLogger();
Log.Information("Inside Startup ctor");
```

If I log to a file, the message "Inside Startup ctor" appears in the file. If I log to the console using serilog-sinks-console, the message does not appear in the console. Logging inside controllers works perfectly.

Am I doing something wrong? Should this work?

**Comment by nblumhardt** [comment]
Hi Kevin - this sounds like it should work, no ideas here, sorry.

**Comment by nblumhardt** [comment]
Hi Kevin, let me know if you found a solution to this, or think it still might be Serilog-related. The folks over at https://gitter.im/serilog/serilog love a puzzle, if so! :-)
