### ISSUE TITLE
Sources of the 3.0.1 release can't be downloaded

### ISSUE THREAD

**Issue by bjoernbusch** [serilog/serilog-sinks-console#19]
For Software Clearing purposes I need the sources for the 3.0.1. release, but when I click on the link in the Releases section, I'm only getting a 500 Internal Server Error.

**Comment by merbla** [comment]
Hi @bjoernbusch,

Try these links

* https://github.com/serilog/serilog-sinks-console/releases/tag/v3.0.1
* https://github.com/serilog/serilog-sinks-console/archive/v3.0.1.zip

**Comment by bjoernbusch** [comment]
Thanks!
