### ISSUE TITLE
Colored output doesn't work with custom console stdout handle

### ISSUE THREAD

**Issue by lennartb-** [serilog/serilog-sinks-console#27]
Not sure if this is a bug or a limitation. We're using a customized console window in our application for debugging purposes. With VS 2017, Microsoft has done some ["debug stdout](https://stackoverflow.com/a/45282476/368354) [redirect magic"](https://developercommunity.visualstudio.com/content/problem/12166/console-output-is-gone-in-vs2017-works-fine-when-d.html) which broke color output with our console window. We fixed that by changing the color manually based on the logging level as suggested in the links above:

```
private static void SetForegroundColor(ConsoleColor color)
{
    using (var hConsoleOut = new SafeFileHandle(CreateFile(OurCustomConsoleFileHandleName, GenericWrite, FileShareWrite, 0, OpenExisting, 0, 0), true))
    {
        SetConsoleTextAttribute(hConsoleOut.DangerousGetHandle(), (ushort) color);
    }
}
```
However, when using the console sink, we now don't have any colored output again. I took a look at the `ConsoleSink `class, and wrapped the calls in the Emit() method with two `SetForegroundColor()` calls that set the color based on the `logEvent.Level` and re-set it to the default color after writing the output.

This already worked to my surprise, but I also had to edit the `ConsoleLoggerConfigurationExtensions` to use my customized version and add some reflection to deal with the referenced internal classes, which is more of a hack than a proper solution.

Is there something I overlooked in the configuration where I could have changed that without changing the existing sink?

Versions:
* Serilog 2.5.0
* Serilog.Sinks.Console 3.1.1

System:
* Windows 10 Pro x64
* WPF application with .NET 4.6.1
* VS 2017 Enterprise 15.4.2

**Comment by nblumhardt** [comment]
Hi! This is a bit of an unknown for me, but have you looked at hooking in via a custom `ConsoleTheme` implementation? HTH!

**Comment by lennartb-** [comment]
Hi, I tried that, but can't get it to work. I tried to just copy the AnsiConsoleTheme, but the Set() method is never called. I configured it like this:

```
 Log.Logger = new LoggerConfiguration()
 .WriteTo.Console(outputTemplate: fileOutputTemplate, theme: new DynConsoleTheme(dict))
.CreateLogger();

```
where `dict `is one of the dictionaries I copied from `SystemConsoleThemes`.

**Comment by lennartb-** [comment]
Okay, it doesn't seem to be a bug. Our application has "Application" as output type, so `IsOutputRedirected ` is always true, even before we do any redirection. I repro'd this with an empty WPF application, so everything is working as intended.

**Comment by nblumhardt** [comment]
Thanks for the follow-up 👍
