### ISSUE TITLE
Add customized JSON Formmter in appsettings.json

### ISSUE THREAD

**Issue by XuefanWu** [serilog/serilog-sinks-console#28]
I created a customized JSON Formatter which extends ITextFormatter
And try to add it to appsetting.json like this:
"WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "CustomizedJSONFormatter"
         // "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
        }
      },

The default jsonFormatter works fine as shown in the commented line.
But I will get an error if I want to add the customized one:
InvalidCastException: Invalid cast from 'System.String' to 'Serilog.Formatting.ITextFormatter'.

Is there anyway to solve this?

Thanks!

**Comment by tsimbalar** [comment]
You need to put in a full type name (the equivalent of `typeof(CustomizedJSONFormatter).FullName` ).

It must contain the type name and the **full namespace** before it.

For example : `typeof(Serilog.Log).FullName` -> `"Serilog.Log"`.

Here is an example in the test suite : 

https://github.com/serilog/serilog/blob/3cd376c8c75ed49ab307c50cd80beaa06cbaecb7/test/Serilog.Tests/Settings/SettingValueConversionsTests.cs#L48-L51

**Comment by XuefanWu** [comment]
Yes. I have tried in that way too, I add the full namespace and everything. But it cause the same error.

**Comment by tsimbalar** [comment]
Ooops, my bad, I gave you a link to the core Serilog repo ...

The behavior seems to be slightly different in in *Serilog.Settings.Configuration*, the one used for `appsettings.json` as I can see from [this test](https://github.com/serilog/serilog-settings-configuration/blob/fae623c627496f00fcfab29f721cd49b2bbed989/test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs#L10-L16). 

From this test, I see you need to provide the full **Assembly qualified name*, which should be something like this : 

```
> typeof(Serilog.Log).AssemblyQualifiedName
"Serilog.Log, Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10"
```

From [MSDN](https://msdn.microsoft.com/fr-fr/library/system.type.assemblyqualifiedname(v=vs.110).aspx) :

> The assembly-qualified name of a type consists of the type name, including its namespace, followed by a comma, followed by the display name of the assembly. The display name of an assembly is obtained using the Assembly.FullName property. 

I'm not sure *Version*, *Culture* and *PublicKeyToken*  are really required though.

**Comment by XuefanWu** [comment]
With the full Assembly qualified name, it works great now.
Thanks!!

**Comment by tsimbalar** [comment]
I'll close the issue :)
