### ISSUE TITLE
restrictedToMinimumLevel not working

### ISSUE THREAD

**Issue by Zemich** [serilog/serilog-sinks-console#29]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

`Log.Logger = new LoggerConfiguration()`
`                .Enrich.FromLogContext()`
`                .MinimumLevel.Fatal()`
`                .WriteTo.Console(restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Verbose)`
`                .CreateLogger();`

`            Log.Verbose("Starting program.");`

This will result in nothing being displayed in the console.

**Comment by GavinSutherland** [comment]
Have you set the minimum level for logging when configuring logging? e.g.

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging(SetLoggingDefaults)
            .UseStartup<Startup>()
            .UseSerilog()
            .Build();

        private static void SetLoggingDefaults(WebHostBuilderContext hostingContext, ILoggingBuilder loggingBuilder)
        {
            // If we don't set a minimum level here any messages below the level of Information won't get logged anywhere
            loggingBuilder.SetMinimumLevel(LogLevel.Trace);
        }

**Comment by nblumhardt** [comment]
`restrictedToMinimumLevel` is a restriction (filter) applied at the sink level. If the level of your logger pipeline is `MinimumLevel.Fatal()`, no events will be generated in the first place.

`restrictedToMinimumLevel` can only reduce the number of log events reaching the sink, not increase it.

HTH!

**Comment by Zemich** [comment]
nblumhardt, sorry my mistake. Thanks for clarifying.
