### ISSUE TITLE
Document the settings' format to specify a theme in XML or JSON config format

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-sinks-console#30]
It would be helpful to extend the README to include example of what specifying the theme via configuration looks like in JSON and XML.

For reference : 
- XML support for *static properties* is available in Serilog v2.6.0+ (issue serilog/serilog#1057 - implemented in PR serilog/serilog#1064 )
- JSON support via Serilog.Settings.Configuration is coming soon (issue serilog/serilog-settings-configuration#73 - PR serilog/serilog-settings-configuration#77 )

I created this issue as result of comments in https://github.com/serilog/serilog-settings-configuration/pull/77#issuecomment-351563659

**Comment by tsimbalar** [comment]
I've been working on that one ....

It's still a work in progress, but here is the current *reference* I have : https://github.com/tsimbalar/serilog-settings-comparison/tree/master/docs

I am actually writing tests (xUnit *theories*) that should pass with : 
- a C# snippet
- a JSON config file
- a xml config file

I haven't covered everything yet, but any feedback is welcome already :) 

Hopefully this will help :
- document all the supported formats
- allow to discover inconstencies between *AppSettings* and *Configuration*
- this can serve as regression tests

**Comment by p-** [comment]
For others searching for a sample to set the serilog sinks console theme. Following seems to work (found in a commit):

```
    "WriteTo": [
      { "Name": "Console", "Args": { "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console" }}
    ]
```

**Comment by tsimbalar** [comment]
Thanks Peter !

Yes, this just landed in _Serilog.Settings.Configuration_ recently :) (see PR serilog/serilog-settings-configuration#77 and issue serilog/serilog-settings-configuration#73 )

Also if that's of any interest, you can find more config samples in here : https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md (shameless plug :))

**Comment by nblumhardt** [comment]
In #39
