### ISSUE TITLE
Any chance to get the coloring for other sinks?

### ISSUE THREAD

**Issue by HansHammel** [serilog/serilog-sinks-console#32]
Well, any chance to separate the coloring functionality to make it work with other sinks, too?

Thanks, OB.

**Comment by nblumhardt** [comment]
Hi Oliver, thanks for getting in touch.

What kinds of other sinks do you have in mind? Any particular classes that would help?

Regards,
Nick

**Comment by HansHammel** [comment]
Well, I had a udp or tcp transport in mind. So, there are two options: Hook up to get the colored ANSI stream of the console output and "materialize" it elsewhere, giving up the benefits of structured logging. Or, have a separate class to reapply the coloring "elsewhere", keeping the benefits (objects) of structured logging, AND, being able to save the stream to a file WITHOUT being cluttered by ANSI color codes (without filtering). It depends on how the coloring is applied. If its deeply baked in, I will appreciate a hook, but the desired solution is a separation of the whole object->template->color processing pipeline...

Greetings, OB.

**Comment by nblumhardt** [comment]
Hi Oliver,

I think 2. will be the better option, given the facilities available today:

1. Use https://github.com/serilog/serilog-formatting-compact to format the events as JSON
2. Send the JSON via TCP/UDP
3. Use https://github.com/serilog/serilog-formatting-compact-reader to reconstitute `LogEvent`s from the JSON
4. Write the `LogEvent`s back through _Serilog.Sinks.Console_ to display

The https://github.com/datalust/clef-tool repository does something similar, worth a look for example usage.

HTH,
Nick

**Comment by HansHammel** [comment]
thx. I'll take a look
