### ISSUE TITLE
Console output is not colored if STDIN is not attached

### ISSUE THREAD

**Issue by Alexander-Nalbandov** [serilog/serilog-sinks-console#42]
Output is not colored when running an .net core 2.0 project in docker non interactive mode.
This gives colored output
`docker run -it  yourimage`
While this doesn't
`docker run yourimage`

MS extensions logger gives colored output

**Comment by nblumhardt** [comment]
Thanks for the note!

I think the current functionality may end up being the desirable one - it's not usually helpful to have ANSI color codes in the output of non-interactive processes; or is there a reason you're unable to pass the `-it` flags when running your container that I'm missing? Thanks!

**Comment by nblumhardt** [comment]
Thanks! :+1:
