### ISSUE TITLE
Weird characters after add console theme

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog-sinks-console#43]
**Bug**

**Serilog.Sinks.Console 3.1.1**

**NET462, Windows 8.1**

**Please describe the current behaviour you are experiencing?**

After try to add custom theme
```xml
<add key="serilog:write-to:Console.theme" value="Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console" />
```
console displays weird characters
![image](https://user-images.githubusercontent.com/21261007/41848916-d03ef962-7887-11e8-84e9-84f1097e4db6.png)
Before this change my config was just simple
```xml
<add key="serilog:write-to:Console" />
```
and all was fine
![image](https://user-images.githubusercontent.com/21261007/41848969-093ad20e-7888-11e8-9b14-25d102ae4a3d.png)

**Please describe the expected behaviour if the ?**
I'm expecting to see normal console colored output

**Comment by adamchester** [comment]
Hi @sungam3r, thanks for stopping by!

This theme you are using relies on Windows 10 support for ANSI colour codes, and you aren’t yet on windows 10.

Try `SystemConsoleTheme.Literate` instead.

**Comment by sungam3r** [comment]
Wow!
