### ISSUE TITLE
Can Console Sink redirect Error and Fatal to Console.Error instead of Console.Out

### ISSUE THREAD

**Issue by MNF** [serilog/serilog-sinks-console#44]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  ** 
-GitHub documentation 

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ x] netCore 2.0
-

**Please describe the current behaviour you are experiencing?**

Issue in serilog-sinks-literate [Ability to direct Error and Fatal to Console.Error instead of Console.Out #6](https://github.com/serilog/serilog-sinks-literate/issues/6)   introduced standardErrorFromLevel parameter.
Is it supported by Console sink?

Is it possible to specify standardErrorFromLevel in appsettings.json?  Example of configuration will be appreciated.

In general when a  pull request with a new feature is accepted, it will be good to ensure that corresponding documentation/wiki is updated as well. Otherwise many useful features are kept hidden.

BTW, the issue template is confusing . In Console sink issue you are  telling:
> **A few questions before you begin:**...
>  This issue list is intended for Serilog core issues. If this issue relates to a sink or related project, please log on the related repository.

**Comment by nblumhardt** [comment]
Hi @MNF - the JSON syntax usually supports everything that the C# method signature provides, so this should work fine. Just including `"standardErrorFromLevel": "Error"` in the JSON config should do it.

Not sure where the issue template is set - thanks for the heads-up, we'll have to correct it.
