### ISSUE TITLE
Custom formatting of a property in a single log entry

### ISSUE THREAD

**Issue by asgerhallas** [serilog/serilog-sinks-console#47]
Hi, 

After quite a few unsuccesful attempts, I have to ask: Is there any way to create a custom format string for use in a single message like this (for console only):

    Log.Information("Recieved {Metrics:my-special-format-for-console}.", metrics);

The variable `metrics` is a dictionary in this case.

PS. Please let me know if this is not the proper place to ask questions :)

**Comment by nblumhardt** [comment]
Hi @asgerhallas - sorry about the lack of response here, I hope you found some method of working around this. There's no built-in feature; overriding `ToString()` on `metrics` would work, if it's not being destructured. Will close under that assumption - if you still need a hand please let us know.
