### ISSUE TITLE
Use JSON-style formatting for top-level `Message` properties when specified

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-console#48]
From https://github.com/serilog/serilog-sinks-file/issues/57 :

- ` `: _I don't want my existing log parser to break (stable formatting since pre-1.0 days)_
- `:j` : _I primarily want machine-readable logs_
- `:l` : _I primarily want human-readable logs_
- `:lj` : _I want to strike a balance - machine-readable as much as possible, but accept some compromises to remove clutter_

The console sink currently uses human-centric/culture-dependent formatting even when `:j` is present in the `Message` token's format specifier. This is inconsistent with the other text-based sinks that use the Serilog built-in `MessageTemplateTextFormatter`.

We should adapt the tests in https://github.com/serilog/serilog/pull/1234, added for this.

**Comment by tsimbalar** [comment]
As discussed in #59 , this will not be fixed as it would force users to change their configuration (provide a custom output template) to restore the initial behavior. Consistency for the sake of consistency is not worth it :P 

`wontfix`
