### ISSUE TITLE
small optimization for padding

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog-sinks-console#54]
**Does this issue relate to a new *feature* or an existing *bug*?**

- [x] improvement

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**

latest

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

all

**Please describe the current behaviour you are experiencing?**

extra [method cal](https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/Rendering/Padding.cs#L42) or [extra zero-length string allocation](https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/Rendering/Padding.cs#L46)

**Please describe the expected behaviour if the ?**

pad > 0 check

**Comment by sungam3r** [comment]
Did not see the check at the beginning of the method.

**Comment by nblumhardt** [comment]
:+1: thanks!
