### ISSUE TITLE
color themes not appearing in output

### ISSUE THREAD

**Issue by WellspringCS** [serilog/serilog-sinks-console#64]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**

Linux Ubuntu 18.04

Code for 3.0 shown here, but I replicated it in netcoreapp2.2 as well.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="serilog.sinks.console" Version="3.1.1" />
  </ItemGroup>

</Project>

```
**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 3.0
- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behaviour you are experiencing?**
log output has no colorization

**Please describe the expected behaviour if the ?**
colorization of output, as per description

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

brand new project, didn't change Startup.cs

Program.cs:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Serilog;

namespace sinks
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateLogger();
            Log.Error("Hello, world!");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```
launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "logging": {
                "engineLogging": false,
                "moduleLoad": false,
                "exceptions": true,
                "browserStdOut": false,
                "programOutput": true
            },
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/sinks.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/34347780/61172930-78417300-a551-11e9-9190-e21ad0e6cb60.png)

Notice that the Serilog log item has no color, however the built-in logger output below it does.

**Comment by nblumhardt** [comment]
Thanks! I think this will be due to the output redirection check here: https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/ConsoleLoggerConfigurationExtensions.cs#L60

Perhaps we consider an `ignoreOutputRedirection` flag or similar? Discoverability will be a problem, though.

**Comment by WellspringCS** [comment]
[nods in agreement, hoping to look like someone who understands the ramifications as relate to discoverability...]

**Comment by michaeltrefry** [comment]
Well, this answers the question I've been banging my head against a wall for several hours trying to solve.
When run locally in windows, I have colors.
When the log is output from a docker container on linux, and output using kubectl logs, no colors.
Are there any work arounds aside from writing my own Console sink, I noticed all the pertinent classes are internal, so I can't even manually configure it.

**Comment by WellspringCS** [comment]
Any timeline for addressing this? Thx in advance.

**Comment by nblumhardt** [comment]
The code involved shouldn't be onerous, it's probably a small change - we're mostly in need of a proposal that works through alternative solutions. My concern with `ignoreOutputRedirection` is that it might take us further towards a bloated `WriteTo.Console()` argument list - @adamchester and I talked briefly about representing this in the `Theme` somehow as an alternative, not sure what that would look like.

**Comment by tjaart** [comment]
Would it make sense to default `ignoreOutputRedirection` to `true` ? What was the reasoning behind the check originally?

**Comment by nblumhardt** [comment]
@tjaart the default avoids writing control sequences when piping the output of a command to a file (e.g. `my-app > results.txt`)

**Comment by tjaart** [comment]
@nblumhardt I've created a PR. I was unsure about the direction of the change, please feel free to make suggestions.

**Comment by tjaart** [comment]
@WellspringCS you can try the latest dev version of Serilog and use the `applyThemeToRedirectedOutput` option in `Write.To.Console()`:

`<PackageReference Include="Serilog.Sinks.Console" Version="4.0.0-dev-00834" />`

I did notice however that Rancher needs an ANSI Color scheme to show colours in output, so if you are working on that platform you have to force the theme. 

```csharp
  Log.Logger = new LoggerConfiguration()
                .WriteTo.Console(theme: AnsiConsoleTheme.Literate, applyThemeToRedirectedOutput: true)
                .CreateLogger();
```

**Comment by WellspringCS** [comment]
Thank you, will do

**Comment by WellspringCS** [comment]
Just had a good opportunity to implement this, but did not see any change. Am I doing something wrong?

using (Ubuntu 18.04):
```
<PackageReference Include="Serilog.Sinks.Console" Version="4.0.0-dev-00834" />
```

```
Log.Logger = new LoggerConfiguration()
  .ReadFrom.Configuration(configuration) // use my settings
  .Enrich.FromLogContext()
  .WriteTo.Console(theme: AnsiConsoleTheme.Literate, applyThemeToRedirectedOutput: true)
  .CreateLogger();
```

This is what I see...

![image](https://user-images.githubusercontent.com/34347780/70625520-2c6e2500-1be8-11ea-90bd-fe8e93604e80.png)

Do I need to change my versions on other Serilog package references for this to work?

**Comment by nblumhardt** [comment]
Hi @WellspringCS - no, console should be enough; might need some more investigation. What terminal are you using? (Default in Ubuntu?) Is your app running under Docker or some other orchestrator that manages output? Thanks!

**Comment by WellspringCS** [comment]
No orchestration, just VSC running on Ubuntu, output going straight to Debug Console in lower pane. HTH...

**Comment by thylux** [comment]
Hi, I'm running on Docker and can replicate both behaviors.
If I run my docker interactively (-it) and execute the app from bash I can see the colors.
If I use the dockerfile ENTRYPOINT to start the application without a shell I don't see colors.

Maybe this clue will help understand this somehow.

**Comment by tjaart** [comment]
@WellspringCS have you tried setting `applyThemeToRedirectedOutput` to `true` and using the `AnsiConsoleTheme` instead of the `AnsiConsoleTheme` theme?

**Comment by tjaart** [comment]
@thylux did you set the `applyThemeToRedirectedOutput ` value to true?

**Comment by thylux** [comment]
@tjaart No. i'm using Serilog.Sinks.Console, Version=3.1.1.0.
What I'm trying to point out is that on a docker environment there's a difference between starting the app using ENTRYPOINT and executing from bash.

I don't know enough of docker to know why but that might give you some hint.

**Comment by vikasjayaswal** [comment]
The Documentation for Serilog.Sinks.Console needs to be updated to include the "applyThemeToRedirectOutput"

**Comment by iappwebdev** [comment]
@WellspringCS Thank you so much for this solution. I have spend hours to resolve this issue with a .NET Web API Application running under IIS Express. I tried several things from [net5.0 project has no color on console output with dotnet watch run](https://github.com/serilog/serilog-aspnetcore/issues/229) and [dotnet watch removes console color](https://github.com/dotnet/aspnetcore/issues/25317) but none of the suggestions worked.

Setting `applyThemeToRedirectedOutput` to `true` in my `appsettings.json` was the solution that worked for me.

**Comment by WellspringCS** [comment]
> @WellspringCS Thank you so much for this solution.

I can't take credit for the solution--only for opening the issue, LOL. Glad the solution offered here (not by me) worked for you, though!
