### ISSUE TITLE
asp.net core 3.0 console sink not working

### ISSUE THREAD

**Issue by dotnetshadow** [serilog/serilog-sinks-console#67]
I'm not sure if this should work with .net core 3.0 libraries, but when I try and configure this sink it says it can't be found. I can configure the RollingFile no problem

```cs
  Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console(restrictedToMinimumLevel: LogEventLevel.Information)
                .CreateLogger();
```

```
<PackageReference Include="Serilog" Version="2.9.0-dev-01119" />
<PackageRefernece Include="Serilog.Sinks.Console" Version="3.1.2-dev-00806 " />
```

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
3.1.2-dev-00806 

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 3.0

**Please describe the current behaviour you are experiencing?**
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'LoggerSinkConfiguration' does not contain a definition for 'Console' and no accessible extension method 'Console' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing a using directive or an assembly reference?)
`

**Please describe the expected behaviour if the ?**

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
*NOTE: A small code sample goes a long way in expediting bug fixes or illustrating an enhancement you are proposing.*

1. Create a new asp.net core 3.0 web application
2. Add required package references
3. Program.cs add 
```cs
  Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console(restrictedToMinimumLevel: LogEventLevel.Information)
                .CreateLogger();
```

**Comment by nblumhardt** [comment]
Hi @dotnetshadow - I'm using Console in a .NET Core 3.0 web application currently, so there might be some other configuration or tooling issue lurking in your setup. Cheers!

**Comment by dotnetshadow** [comment]
@nblumhardt that's great to know cheers.
Can I ask what nuget packages and versions you are using?
Perhaps you could provide a snippet of how you set it up?

**Comment by nblumhardt** [comment]
Super-simple setup, essentially just:

```csharp
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console(theme: AnsiConsoleTheme.Grayscale)
                .CreateLogger();
```

Project refs:

```xml
    <PackageReference Include="Serilog" Version="2.8.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.0-*" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.0.0-*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

HTH

**Comment by dotnetshadow** [comment]
Thanks that worked,

I was using these packages which were probably causing the issue. I suspect it's the **Serilog.Extensions.Hosting**
```xml
    <PackageReference Include="Serilog" Version="2.9.0-dev-01119" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.0.0-dev-00059" />
    <PackageRefernece Include="Serilog.Sinks.Console" Version="3.1.2-dev-00806 " />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.1-dev-00771" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="3.0.0-dev-00019" />
```

**Comment by skomis-mm** [comment]
Hi, @dotnetshadow . I think the problem is with misspelling:
<PackageRefe**rne**ce Include="Serilog.Sinks.Console" Version="3.1.2-dev-00806 " />

**Comment by dotnetshadow** [comment]
@skomis-mm hahaha you are so right can't believe I didn't pick that up
