### ISSUE TITLE
The Great Console Unification

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-console#7]
From https://github.com/serilog/serilog-sinks-literate/issues/17.

We've now had experience with three different console sink designs, this one, `ColoredConsole` and `LiterateConsole`.

Each has strengths and weaknesses; for example, literate has nice presentation, but `Console` can accept a custom formatter and produce valid JSON if required.

It's time to unify all of these. There are, as always, options. A strawman proposal:

 * Extend this sink (_Serilog.Sinks.Console_) so that it supports everything we would like it to (as a 3.0/breaking change release)
 * Make _Serilog.Sinks.ColoredConsole_ and _Serilog.Sinks.LiterateConsole_ into thin wrappers around _Serilog.Sinks.Console_ that configure it with default palettes/formatting options to achieve (mostly?) the original output of those sinks
 * Mark `WriteTo.LiterateConsole()` and `WriteTo.ColoredConsole()`, and the corresponding NuGet packages, obsolete, directing users to `WriteTo.Console()`

Things I think we want without doubt:

 - [x] All of the currently-available options in the three existing sinks:
    * Typical formatting options: message template or custom `ITextFormatter`, culture
    * Standard minimum level configuration
    * Minimum-level-to-STDERR
 - [x] Palette control
    * By default, should look roughly like the current literate console (but we might update the color scheme, e.g. along the lines of VSCode?)
    * By default, uses ANSI color codes and make sure presentation is first-class in `cmd.exe`, `bash` (dark) and `PowerShell` (default blue) terminals
    * Custom ANSI and Windows palette implementations (`LiterateConsole` and `ColoredConsole` might use Windows ones by default, but we'd strongly encourage ANSI through docs/examples)
    * Selectable built-in "no color" palette
 - [x] Support for `{Properties}`
 - [x] Support for `{Message:l}` (this would probably be in the default template, since color would also be on by default, making property value delimiters (`"`) redundant
 
Stretch/later goals:

 - [ ] Some level palette control via XML/JSON configuration (perhaps just choosing color/no-color, or palette-by-`Type`)

Other thoughts:

  * Do we want to keep using the default "Serilog-style" rendering of things like dictionaries and `StructureValue`, or would the output be more predictable/meaningful for people if we instead printed complex values as (syntax-highlighted) JSON?

**Comment by adamchester** [comment]
👍

**Comment by adamchester** [comment]
> Do we want to keep using the default "Serilog-style"

I would be OK with printing highlighted JSON, it's easier to copy/paste/manipulate and more predictable for users I think.

**Comment by frg** [comment]
Is the release date for these known, yet? Great work on this! :)

**Comment by merbla** [comment]
@frg sorry, no date as yet.  With  serilog/serilog#977 merged it opens up other sinks to start some required changes.

**Comment by nblumhardt** [comment]
Hoping to have some time to push this forward in the next day or two, but it'll be a while until it's ready. There are some non-trivial weaknesses in `LiterateConsole` that need to be resolved in the unified version :-)

**Comment by frg** [comment]
@nblumhardt Great news! 👍

**Comment by nblumhardt** [comment]
On NuGet now in `3.0.0-dev-00732`

**Comment by nblumhardt** [comment]
Any and all testing/validation appreciated, BTW :-)

**Comment by Noctis-** [comment]
Time flies ...last time i've looked at these V2 was breaking our V1 things ... and here we are ... V3, and we didn't have the time to update :)
Good work 👍
