### ISSUE TITLE
Wrong Template when running over SSH

### ISSUE THREAD

**Issue by DanielPeinhopf** [serilog/serilog-sinks-console#74]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
Version 3.1.2-dev-00824

**What is the target framework and operating system affected by this issue?**

- [x] netCore 3.0
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behaviour you are experiencing?**
I'am using a custom formatting template which is used correctly when running the app locally.
```
[SRV] 21:36:42 [1] WRN ConsoleApp1.Program: Hello log
```

But when executing the app on a RaspberryPi over SSH my template is ignored and a different template is used but also different from the default-template.
```
20:27:01  1  WRN ConsoleApp1.Program  Hello log
```
Why is this happening?

**Please describe the expected behaviour if the ?**
The defined custom template should be used, also when running over SSH.

**How to reproduce:**
``` C#
class Program
{
	static void Main(string[] args)
	{
		var template = "[SRV] {Timestamp:HH:mm:ss} [{ThreadId}] {Level:u3} {SourceContext}: {Message:lj}{NewLine}{Exception}";

		var logger = new LoggerConfiguration()
			.Enrich.WithThreadId()
			.WriteTo.Console(outputTemplate: template)
			.CreateLogger()
			.ForContext(typeof(Program));

		logger.Warning("Hello log");
	}
}
```

**Comment by nblumhardt** [comment]
I'm not sure what's going on here, but I'd guess the issue is between the app and SSH, rather than being related to output templating directly. The second, SSH, example is very similar in layout to the template you've supplied, so perhaps ANSI color coding is upsetting things?

To test this theory you can try:

```csharp
.WriteTo.Console(outputTemplate: template, theme: ConsoleTheme.None)
```

Let me know if this helps,
Nick

**Comment by DanielPeinhopf** [comment]
Yes, your are absolutely right. I'ts a problem with SSH or PuTTY.
I've now tested the following scenarios:

1. Desktop console of Raspbian: Works correctly
2. PuTTY with default settings: Wrong template
3. PuTTY with disabled control characters: Works correctly
4. ConsoleTheme.None: Works correctly

So for me i'll use ConsoleTheme.None for now but i've no idea why the template string characters are interpreted as control characters.

**Comment by nblumhardt** [comment]
The themes other than `ConsoleTheme.None`, on Linux, will use ANSI color codes/escape sequences, so there's a good chance this is triggering the behavior. The console sink just writes to `STDOUT`. Thanks for the follow-up!
