### ISSUE TITLE
Add netcoreapp2.0 target

### ISSUE THREAD

**Issue by kerams** [serilog/serilog-sinks-console#78]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
All

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
.NET Core 2.0+

**Please describe the current behaviour you are experiencing?**
When adding this package to a .NET Core 3.1 project, the nearest framework [is resolved to](https://nugettoolsdev.azurewebsites.net/5.3.0/get-nearest-framework?project=netcoreapp3.1&package=net45%0D%0Anetstandard1.3%0D%0Anetstandard2.0%0D%0Anetcoreapp1.1) `netcoreapp1.1`, not `netstandard2.0`. As a result, `System.Console`, `System.Runtime.InteropServices` and `System.Runtime.InteropServices.RuntimeInformation` are considered transitive dependencies (and part of the Paket lock file in my case), even though these APIs are available to my taget framework directly by virtue of it implementing `netstandard2.0`.

**Please describe the expected behaviour if the ?**
Expecting `Serilog` to be the only transitive dependency for .NET Core 2.0 projects or higher.

**Comment by nblumhardt** [comment]
Thanks for the heads-up 👍

**Comment by nblumhardt** [comment]
Fixed in #80
