### ISSUE TITLE
PropertiesTokenRenderer - unnecessary empty structure ("{}") printed when no properties are present

### ISSUE THREAD

**Issue by Eran-BenShahar** [serilog/serilog-sinks-console#79]
Currently, given the message template = `"[{Timestamp:yyyy-MM-dd HH:mm:ss.ffff} {Level:u3}] {Message:l} {Properties}"` and providing no properties, an empty structure is printed:
```
[2020-01-07 15:00:24.6515 INF] Program started {Version="1.0.0.0"}
[2020-01-07 15:00:24.6920 INF] Moduel 1 Starting {}
[2020-01-07 15:00:24.6934 INF] Moduel 2 Starting {}
[2020-01-07 15:00:24.6945 INF] Moduel 3 Starting {}
[2020-01-07 15:00:24.7052 INF] Module 1 DoSomething Starting {Item="Foo"}
[2020-01-07 15:00:24.7087 INF] Module 2 DoSomething Starting {Item="Bar"}
```
I think that it would be nicer to not have that empty structure printed every time, like so:
```
[2020-01-07 15:00:24.6515 INF] Program started {Version="1.0.0.0"}
[2020-01-07 15:00:24.6920 INF] Moduel 1 Starting
[2020-01-07 15:00:24.6934 INF] Moduel 2 Starting
[2020-01-07 15:00:24.6945 INF] Moduel 3 Starting
[2020-01-07 15:00:24.7052 INF] Module 1 DoSomething Starting {Item="Foo"}
[2020-01-07 15:00:24.7087 INF] Module 2 DoSomething Starting {Item="Bar"}
```

Is this something that sounds reasonable?

**Comment by nblumhardt** [comment]
Thanks for the note. The current behavior is by design, though I agree we could improve on this.

The core issue is that even if the renderer omitted the `{}`, we'd be left with an annoying trailing whitespace. There isn't currently a clean way to do control whether or not to print the preceding space, so we've chosen the simpler route.

I think an alternative output templating system would be the best solution here. Some kind of conditional rendering is needed, but it would be nicer to bake this in from the start, rather than try to retrofit it to the existing output templates in a nonbreaking way.

**Comment by Eran-BenShahar** [comment]
You actually touched on the other issue we had which is the trailing/preceding whitespace.
We had that when we used an optional property in the message template (`{Scope}` which is the MS.Extensions scope). 
In that case I think the  `EventPropertyTokenRenderer` simply doesn't print anything and we are left with the whitespace that was present in the message template.

So I agree, that a better solution is required.
Do you have something planned?
I would like to contribute, but I just started learning this product and I'm not sure I know where would be the correct place to add conditional rendering.
Maybe it should be a a feature at the base library?

**Comment by nblumhardt** [comment]
Thanks for your reply, @Eran-BenShahar 👍 

Serilog supports pluggable `ITextFormatter`s with all of its text-based sinks; for the console, this might mean foregoing theme support (or replicating what's here), but implementing an `ITextFormatter` would probably still be the best starting point.

This could be plugged in from a separate library; some extension methods might clean up configuration, but roughly, you'd enable:

```csharp
    .WriteTo.Console(new MyFormatter("string with conditionals"))
```

The parser and evaluator for the new formatting syntax would need to be built from scratch, but, the expression language in _Serilog.Filters.Expressions_ covers property access expressions, indexers, `Functions(Prop, 'something')`, maths, etc., over log events. It might be a useful starting point for a syntax along the lines of:

```
[{Timestamp:yyyy-MM-dd HH:mm:ss.ffff} {Level:u3}] {Message:l}{#if Length(Properties) > 0} {Properties}{#/if}
```

(Completely arbitrary made-up syntax in the example, but illustrates the kinds of things we'd need to support.)

Another option would be to build an `ITextFormatter` based on a binding to an existing templating library like Handlebars.NET, which would be very interesting, but which I haven't investigated yet.

Let me know if you decide to give either approach a shot 😎 

HTH!
Nick

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-expressions has `ExpressionTemplate` with conditionals, which now support this scenario.
