### ISSUE TITLE
v4 stable release

### ISSUE THREAD

**Issue by megakid** [serilog/serilog-sinks-console#81]
Any chance we could do a merge to `master` and release a v4 of this sink?  I'm currently using v3.1.1 and using reflection to set and share a `syncRoot` over multiple ConsoleSinks, then I saw a recently merged PR that solves this.

**Comment by nblumhardt** [comment]
Thanks for the nudge; I've created #82 to make this a bit more visible, and will update it when I've had a chance to review the release contents. Cheers!

**Comment by silkfire** [comment]
@nblumhardt When is v4 actually going to be released? I can see that the last NuGet release was in October 2017. Any reason for this long delay?

**Comment by nblumhardt** [comment]
Time to do this! Thanks for the nudge @silkfire - will follow up in #82
