### ISSUE TITLE
When using string interpolation, colors do not show

### ISSUE THREAD

**Issue by Fraysa** [serilog/serilog-sinks-console#90]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog Console Sink is affected by this issue?  Please list the related NuGet package.**
Everything above C# 6.

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [X] netCore 1.0
- [X] 4.7
- [X] 4.6.x
- [X] 4.5.x

**Please describe the current behaviour you are experiencing?**
When using string interpolation, colors do not show so you're forced to use composite formatting.

**Please describe the expected behaviour if the ?**
It should color the parameters regardless.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
*NOTE: A small code sample goes a long way in expediting bug fixes or illustrating an enhancement you are proposing.*
Executing the following produces colors normally:
`Log.Information("Hey, {0}, this is a {1}!", parameter1, parameter2);`

Executing the following does not produce any colors:
`Log.Information($"Hey {parameter1}, this is a {parameter2}!");`

**Comment by nblumhardt** [comment]
Thanks for the note! This is by design; string interpolation shouldn't be used with Serilog; there's some discussion in: https://nblumhardt.com/2015/01/c-6-string-interpolation-and-serilog/ - cheers
