### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by willapp** [serilog/serilog-sinks-console#93]
The `StringWriter` created here:
https://github.com/serilog/serilog-sinks-console/blob/eafe7d50cd9c2255b25ce3110eee8382ae5c0561/src/Serilog.Sinks.Console/Sinks/SystemConsole/ConsoleSink.cs#L61

is never disposed Looks like a potential memory leak?

**Comment by nblumhardt** [comment]
Thanks for the note and PR! No, there's no resource leak here, StringWriter over StringBuilder is all in managed code (it's an unfortunate wrinkle in the design of System.IO and C# in general - the code errs on the side of correctness rather than go through the unnecessary `using` ceremony here).

**Comment by rafaelsc** [comment]
[StringWriter.Dispose() ](https://referencesource.microsoft.com/#mscorlib/system/io/stringwriter.cs,70) just block the StringWriter to be reused. Don't free any additional memory.
