### ISSUE TITLE
Add support C# 8 nullable reference types

### ISSUE THREAD

**Issue by rafaelsc** [serilog/serilog-sinks-console#97]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What is the target framework and operating system affected by this issue? Please see [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netstandard2.1. **NEW**
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Describe the solution you'd like**
Enable [nullable-references](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in Serilog and add update the codebase to support the nullable reference types in .NET Core 3.0 and 3.1.

**Additional context**
Links about the *Nullable reference types *:
 - [Nullable reference types (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)
 - [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
 - [Introducing Nullable Reference Types in C#](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/)

**Comment by rafaelsc** [comment]
Related - https://github.com/serilog/serilog/issues/1455

**Comment by jwdonahue** [comment]
I would really love to see this feature enabled soon. This looks scary:

```
  var logger = loggerMinimumLevelConfiguration
           !.Enrich?.With(enricher)
           ?.WriteTo.File(logPathFileName,
                   rollingInterval: interval,
                   outputTemplate: outputTemplate)
           ?.CreateLogger();
  Verify.IsNotNull(logger);
```

**Comment by Numpsy** [comment]
I think the nullability annotations should be enabled in the latest version now.
